config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :followings, only: [:new, :create, :destroy]
  resources :opinions, only: [:index, :new, :create]

  namespace :api, :defaults => {:format => :json} do
    resources :users
  end

  root to: 'sessions#new'
  get '*path' => redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :fullname, length: { maximum: 50 }

  has_many :following_followings, class_name: 'Following',
                                  foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, source: :following, through: :following_followings

  has_many :following_followers, class_name: 'Following',
                                 foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, source: :follower, through: :following_followers

  has_many :opinions, foreign_key: 'author_id', dependent: :destroy

  has_many :cover_images, -> { where(image_type: 'cover') }, inverse_of: :user,
                                                             class_name: 'Photo', dependent: :destroy
  accepts_nested_attributes_for :cover_images

  has_many :profile_images, -> { where(image_type: 'profile') },
           inverse_of: :user, class_name: 'Photo', dependent: :destroy
  accepts_nested_attributes_for :profile_images

  has_many :comments, dependent: :destroy

  def self.initialize_with_images(user_params)
    @user = User.new(user_params)
    photo_cover = Photo.new(user_id: @user.id, image_type: 'cover')
    photo_cover.image = File.new(Rails.root.join('public', 'images', 'cover.jpg'))
    photo_profile = Photo.new(user_id: @user.id, image_type: 'profile')
    photo_profile.image = File.new(Rails.root.join('public', 'images', 'profile2.png'))
    @user.cover_images << photo_cover
    @user.profile_images << photo_profile
    @user
  end

  def follow(user)
    following = Following.new(follower_id: id, followed_id: user.id)
    following.save
    true
  rescue StandardError
    false
  end

  def unfollow(user)
    Following.where(follower_id: id, followed_id: user.id).first.destroy
    true
  rescue StandardError
    false
  end

  def following?(user)
    !Following.where(follower_id: id, followed_id: user.id).empty?
  end

  def visible_opinions
    ids = followings.ids << id
    Opinion.where(author_id: ids).order(id: :desc)
  end

  def unfollowings
    unfollowing_ids = User.ids - (followings.ids << id)
    User.where(id: unfollowing_ids).order(id: :desc)
  end

  def profile_image?
    if profile_images.first
      profile_images.first.image_file_name ? true : false
    else
      false
    end
  end

  def cover_image?
    if cover_images.first
      cover_images.first.image_file_name ? true : false
    else
      false
    end
  end

  def followed_by(user)
    shared_connections = followings - (followings - user.followers)
    shared_connections -= [user]
    shared_connections -= [self]
    return false if shared_connections.empty?

    shared_connections.sample
  end

  def as_json(options = {})
    { :name => self.username,
      :id => self.id }
  end
end

app/controllers/api/users_controller.rb
class API::UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.json { render :json => @users }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_authorization, except: %i[new edit create]
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all.order(id: :desc).includes(:opinions, :profile_images, :followings, :followers)
  end

  def show
    @user = User.find(params[:id])
    @followers = @user.followers.includes(:profile_images)
    @comment = Comment.new
  end

  def new
    @user = User.new
    @user.cover_images.build
    @user.profile_images.build
    render layout: 'welcome' unless signed_in?
  end

  def edit
    @user = User.find(params[:id])
    @cover_image = @user.cover_images.build unless @user.cover_images.exists?
    @profile_image = @user.profile_images.build unless @user.profile_images.exists?
    render 'users/edit_form'
  end

  def create
    @user = User.initialize_with_images(user_params)

    if @user.save
      sign_in @user
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash[:notice] = 'That username is taken, try a different one...'
      redirect_to new_user_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Edit successful.'
      sign_in @user
      redirect_to user_path @user
    else
      flash[:notice] = "Edit wasn't successful."
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    user = current_user
    if user.destroy
      sign_out
      flash[:notice] = 'Acount deleted'
    else
      flash[:notice] = "Acount delete wasn't successful."
    end
    redirect_to root_path
  end

  private

  def set_user
    if params[:id].to_i > User.last.id.to_i
      redirect_to root_path
      return
    end
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :fullname, :photo, :coverimage,
                                 cover_images_attributes: %i[id image image_type],
                                 profile_images_attributes: %i[id image image_type])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_button(user)
    return if current_user == user

    if current_user.following?(user)
      render 'users/already_following', user: user
    else
      render 'users/follow_button', user: user
    end
  end

  def edit_button(user)
    render 'users/edit_button', user: user if current_user == user
  end

  def followed_by_notice(user)
    if current_user.followed_by(user)
      render 'users/followed_by', user: current_user.followed_by(user)
    else
      'You can follow this user.'
    end
  end

  def last_three_user
    User.all[0,12]
  end

  def show_avatar(user)
    render 'users/show_avatar', user: user
  end
end

app/views/users/_already_following.html.erb
<div class="btn btn-primary">
  <%= link_to 'Unfollow', following_path(id: user.id), method: :delete, class: "text-white" %>
</div>

app/views/users/_edit_button.html.erb
<%= link_to 'Edit', edit_user_path(user), class: 'btn btn-secondary text-white' %>

app/views/users/_follow_button.html.erb
<div class="btn btn-primary">
  <%= link_to 'Follow', followings_path(id: user.id), method: :post,
  class: 'text-white' %>
</div>

app/views/users/_followed_by.html.erb
<span class="text-muted text-wrap word-break">
  Followed by
  <span class="text-primary followed_by">
    <%= link_to "#{user.username}", user_path(user.id), class: "text-primary" %>
  </span>
</span>

app/views/users/_followers.html.erb
<div class="p-3 followers">
  <% @followers.each do |follower| %>
  <div class="media my-3">
    <%= image_tag follower.profile_images.first.image.url,
     class: 'align-self-center mr-3 rounded-circle' %>
    <div class="media-body">
      <h5 class="mt-0">
          <%= link_to "#{follower.fullname}", user_path(follower.id)%>
      </h5>
      <p>@<%= follower.username %> </p>
    </div>
  </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="create_new_scientist text-center">
  <h4>Create New User</h4>
  <%= form_with(model: user, local: true) do |form| %>


    <div class="d-flex justify-content-center">
      <div class="field mx-1">
        <%= form.label :username, class: 'py-2' %>
        <%= form.text_field :username, required: true, maxlength: 40,
        class: 'py-4 text-center m-1', spellcheck: false %>
      </div>

      <div class="field mx-1">
        <%= form.label :fullname, class: 'py-2' %>
        <%= form.text_field :fullname, required: true, maxlength: 40,
        class: 'py-4 text-center m-1', spellcheck: false %>
      </div>
    </div>
  <div class="note">
    <p>You can change your profile photo and cover photo after signing in...</p>
  </div>
    <div class="actions d-flex justify-content-center align-items-center pl-5 mt-4">
      <%= form.submit 'Create User and Sign In', class: 'create-user-button btn btn-primary p-0 px-3' %>
      <i class="fas fa-user-plus text-primary px-1 pl-3"></i>
      <i class="fas fa-sign-in-alt text-primary px-1"></i>
    </div>
  <% end %>
</div>

app/views/users/_right_profile.html.erb
<% content_for :right do %>
<div class="right_profile">
  <div class="d-flex align-items-center justify-content-center py-3">
    <%= image_tag @user.profile_images.first.image.url,
     class: 'align-self-center rounded-circle' %>
  </div>
  <div class="text-center">
    <%= follow_button @user %>
  </div>
  <div class="text-center">
    <%= edit_button @user %>
  </div>

  <h4 class="text-center my-2"> <%= @user.fullname %> </h4>
  <h4 class="text-center"> @<%= @user.username %> </h4>

  <div class="container-fluid mt-4">
    <div class="row stats">
      <div class="col-4 py-4 px-1 tweets">
        <p class="text-center"><%= @user.opinions.count %></p>
        <h5 class="text-center pt-2">Tweets</h5>
      </div>
      <div class="col-4 py-4 px-1 followings">
        <p class="text-center"><%= @user.followings.count %></p>
        <h5 class="text-center pt-2">Following</h5>
      </div>
      <div class="col-4 py-4 px-1 followers">
        <p class="text-center"><%= @user.followers.count %></p>
        <h5 class="text-center pt-2">Followers</h5>
      </div>
    </div>
  </div>

  <h4 class="text-center mt-3 followed_by" >FOLLOWED BY</h4>

  <%= render 'users/followers', followers: @user.followers %>

</div>
<% end %>

app/views/users/_show_avatar.html.erb
<%= image_tag user.profile_images.first.image.url,
class: 'sign-in-avatar rounded-circle' %>

app/views/users/_who_to_follow.html.erb
<% content_for :right do %>
  <div class="p-3 who_to_follow text-wrap overflow-hidden">
    <h4 class="text-center py-3 sticky-top">WHO TO FOLLOW</h4>
    <% unfollowings.each do |unfollowing| %>
      <div class="media my-3">
        <%= image_tag unfollowing.profile_images.first.image.url,
         class: 'align-self-center mr-3 rounded-circle' %>
        <div class="media-body">
          <div class="mt-0 followed_by_notice text-wrap text-break text-muted">
              <%= link_to "#{unfollowing.username}", user_path(unfollowing.id)%>
              <p><%= followed_by_notice unfollowing %></p>
          </div>
        </div>
        <div class="align-self-center text-muted">
          <%= follow_button(unfollowing) %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/edit_form.html.erb
<% content_for :right do %>
  <div class="my-5 mx-auto W-100 text-center">
    <div class="btn btn-danger mx-auto my-5 text-center">
      <%= link_to 'Delete My Account', user_path(current_user.id),
      class: 'text-white mx-auto my-5', method: :delete,
      data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<div class=" edit_user mb-5">
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="note text-center mt-5">
    <p>You can change your name, username, profile photo,
      <br> and cover photo(less than 1MB) ...</p>
  </div>
<div class="container-fluid">
  <div class="d-flex mt-4 row">
    <div class="field col-12 text-center">
      <%= form.label 'Username:', class: 'py-2' %>
      <%= form.text_field :username, required: true, maxlength: 40,
       class: 'py-4 px-1 w-25 text-center', spellcheck: false %>
    </div>

    <div class="field col-12 text-center">
      <%= form.label 'Full name:', class: 'py-2' %>
      <%= form.text_field :fullname, required: true, maxlength: 40,
       class: 'py-4 px-1 w-25 text-center', spellcheck: false %>
    </div>
</div>

    <div class="row mt-4">
    <div class="col-12 text-center mt-4">


      <%= form.fields_for :cover_images do |foto_form| %>
        <%= foto_form.label :image, "Upload your cover image:" %><br />
              <%= foto_form.file_field :image, class: "mt-3",
              accept: "image/*" %>
        <% if @user.cover_images.exists? %>
          <% @user.cover_images.each do |photo| %>

            <%= image_tag photo.image.url %>
          <% end %>
        <% end %>

        <%= foto_form.text_field :image_type, value: 'cover', hidden: true %>
      <% end %>
    </div>

    <div class="col-12 text-center mt-4">
     <%= form.fields_for :profile_images do |foto_form| %>
        <%= foto_form.label :image, "Upload your profile image:" %><br />
                <%= foto_form.file_field :image, class: "mt-3 text-center",
                accept: "image/*" %>
        <% if @user.profile_image? %>
          <% @user.profile_images.each do |photo| %>
            <%= image_tag photo.image.url %>
          <% end %>
        <% end %>

        <%= foto_form.text_field :image_type, value: 'profile', hidden: true %>
     <% end %>
    </div>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-12 text-center">
      <div class="actions mt-4 pt-3 text-center">
        <%= form.submit 'Save Changes', class: 'btn btn-success pb-4', id: 'save-changes' %>
      </div>
    </div>
  </div>


<% end %>
</div>

app/views/users/index.html.erb
<%= render 'users/who_to_follow', unfollowings: current_user.unfollowings %>
<div class="ribbon mt-4">
  <h2 class="text-center">Scientists</h2>
</div>
<div class="scientists d-flex flex-wrap justify-content-between mx-auto px-4 mb-5">
  <% @users.each do |user| %>
    <div class="card mx-auto my-2 shadow" style="width: 15rem;">
      <%= image_tag user.profile_images.first.image.url,
       class: 'card-img-top rounded-circle mx-auto mt-2' %>
        <div class="card-body d-flex flex-column justify-content-around">
          <div>
            <h5 class="card-title text-wrap text-center my-0">
              <%= user.fullname %> <br>
              @<%= user.username %>
            </h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex my-0">
              <span>Reports: </span>
              <span class="ml-auto"><%= user.opinions.count %></span>
            </li>
            <li class="list-group-item d-flex my-0">
              <span>Followings:</span>
              <span class="ml-auto"><%= user.followings.count %></span>
            </li>
            <li class="list-group-item d-flex my-0">
              <span>Followers:</span>
              <span class="ml-auto"><%= user.followers.count %></span>
            </li>
          </ul>
          <div class="bg bg-secondary rounded text-white my-auto latest p-1">
            <p class="text-center">Latest Report:</p>
            <p class="card-text text-center">"<%= last_tweet user %>"</p>
          </div>
        </div>
      <div class="buttons text-center mb-2">
        <%= link_to 'Profile', user, class:'btn btn-primary text-white ml-auto' %>
        <%= follow_button user %>
        <%= edit_button user %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

<%= sign_in_page_link %>

app/views/users/show.html.erb
<div class="show_user">
<div class="cover_image">
  <% if @user.cover_image? %>
    <% @user.cover_images.each do |photo| %>
      <%= image_tag photo.image.url %>
    <% end %>
  <% end %>
</div>

<% render 'users/right_profile' %>

<%= render 'opinions/recent_tweets', tweets: @user.opinions.order(id: :desc) %>

</div>