config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :followings, only: [:new, :create, :destroy]
  resources :opinions, only: [:index, :new, :create]

  namespace :api, :defaults => {:format => :json} do
    resources :users
  end

  root to: 'sessions#new'
  get '*path' => redirect('/')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reporting Scientists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="https://png.pngtree.com/png-clipart/20200225/original/pngtree-science-icon-png-image_5273869.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2c6133bcaa.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,800;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Sue+Ellen+Francisco&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <div class="container-fluid">
    <div class="row">
      <div class="col-2 m-0 p-0">
        <!-- left_bar -->
        <div class="left_bar">

            <div class="media p-3 current_user d-flex">
              <%= image_tag current_user.profile_images.first.image.url,
               class: 'align-self-center mr-3 rounded-circle' %>
              <div class="media-body align-self-center text-break text-wrap">
                <%= link_to "#{current_user.username}",
                  user_path(current_user.id), class: 'text-break text-center text-wrap'%>
              </div>
            </div>

            <div class="container-fluid m-0 p-0 stats">
              <div class="row m-0 p-0">
                <div class="col-6 py-4">
                  <p class="text-center">
                    <%= current_user.followings.count %>
                  </p>
                  <h5 class="text-center">Following</h5>
                </div>
                <div class="col-6 py-4 followers">
                  <p class="text-center">
                    <%= current_user.followers.count %>
                  </p>
                  <h5 class="text-center">Followers</h5>
                </div>
              </div>
            </div>

            <div class="container-fluid navigation p-0">
              <div class="link_to p-3">
                <i class="fas fa-user-cog"></i>
                <%= link_to "PROFILE", user_path(current_user.id), class: 'ml-1' %>
              </div>
              <div class="link_to p-3">
                <i class="fas fa-vials"></i>
                <%= link_to 'REPORTS', opinions_path,
                class: 'ml-1' %>
              </div>
              <div class="link_to p-3">
                <i class="fas fa-users"></i>
                <%= link_to 'SCIENTISTS', users_path,
                class: 'ml-1' %>
              </div>
              <div class="link_to p-3">
                <i class="fas fa-sign-out-alt pl-1"></i>
                <%= link_to "SIGN OUT", session_path(session[:current_user_id]),
                method: :delete, class: 'ml-1' %>
              </div>
            </div>

            <%= yield :left %>

        </div>
      </div>
      <div class="col-10 m-0 p-0 overflow-hidden">
        <!-- top_bar && mid_wrapper && right_bar -->
        <div class="row">
          <div class="col-12 p-0 m-0">
            <!-- top_bar -->
            <div class="top_bar mb-0">
              <div class="wrapper d-flex align-items-center mb-0">

                <div class="notice ml-5">
                  <p id="notice"><%= notice %></p>
                </div>

                <div class="prompt d-flex align-items-center ml-auto">
                  <div class="top_logo">
                    <i class="fas fa-vial"></i>
                  </div>

                  <div class="prompt text-nowrap ml-4">
                    Reporting Scientists
                  </div>
                </div>

              </div>
              <%= yield :top %>

            </div>
          </div>
        </div>

        <div class="row">
          <!-- mid_wrapper && right_bar -->

            <!-- mid_wrapper -->
            <div class="col-9 mid-wrapper pl-0 pr-5 pb-0">
              <%= yield  %>
            </div>

            <!-- right_bar -->
            <div class="col-3 m-0 right_bar m-0 pr-0 pl-0">
              <%= yield :right %>
            </div>

        </div>

      </div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reporting Scientists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2c6133bcaa.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Sue+Ellen+Francisco&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,800;1,400&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="welcome d-flex flex-column justify-content-center align-items-center">
      <div class="prompt">
        <div class="quick-sign-in text-white">
          <% last_three_user.each do |user| %>
          <%= link_to show_avatar(user), sessions_path(user.username), method: :post, title: user.fullname %>
          <% end %>
        </div>
        <h1 class="invitation m-2 display-1 p-5 rounded-pill">Reporting Scientists</h1>
        <div class="by_me">
          <i class="fab fa-twitter"></i>
          <span>Recreation by <a href="https://kubilaycaglayan.com" target="_blank">Kubilay Çağlayan</a></span>
        </div>
      </div>
      <div class="bg-white p-4 rounded text-center">
        <p id="notice"><%= notice %></p>
      <%= yield %>
      </div>
    </div>
  </body>
</html>